---

- hosts: all
  become: true
  tasks:

  - name: install updates (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: install the apache2 and php package for Ubuntu
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 and php package for CentOS
    package:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: install Samba file share (Ubuntu)
    package:
      name: samba
      state: latest
    when: ansible_distribution == "Ubuntu"
