- name: restart_httpd
  service:
    name: httpd
    state: restarted
  when: apache_distribution == "CentOS"

- name: restart_apache
  service:
    name: apache2
    state: restarted
  when: apache_distribution == "Ubuntu"
